version: "3.9" #version of docker-compose
services:
  mysql:
    container_name: mysql
    image: mysql:8.2
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=root
    # volumes:
    # - ./data:/var/lib/mysql                         #database data volume
    # - ./src/main/db:/docker-entrypoint-initdb.d/:ro #database files called when the container is built and started for the first time
  web:
    container_name: tomcat
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mysql
